class AirplanesController < ApplicationController

    # skip the check for the authenticity token which is generated by the form_with 
    # helper - we are submitting out form from our React frontend (eventually), so we won't have this token
    skip_before_action :verify_authenticity_token, raise: false


    def new  # /airplanes/new

        @airplane = Airplane.new

    end #new

    def create
    
        @airplane = Airplane.create!(

            name: params[:airplane][:name],
            row: params[:airplane][:row],
            column: params[:airplane][:column]
            
        ) 

        # if @airplane.persisted?
        #     render json: @airplane
        # else
        #     render json: { error: 'Count not create airplane' }, status: 422
        # end

        redirect_to airplanes_path

    end #create

    def index
        @airplane = Airplane.all
    end #index

    def show
        
    end # show

    def update
        
    end #update

    def destroy
        
    end #destroy

end
