class FlightsController < ApplicationController

    # skip the check for the authenticity token which is generated by the form_with 
    # helper - we are submitting out form from our React frontend (eventually), so we won't have this token
    skip_before_action :verify_authenticity_token, raise: false

    def new
        
    end #new

    def create

        flight = Flight.create content: params[:content]

        if flight.persisted?
            render json: flight
        else
            render json: { error: 'Count not create flight' }, status: 422
        end
        
    end #create

    def index
        render json: Flight.all
    end #index

    def show
        
    end # show

    # def update
        
    # end #update

    def destroy
        
    end #destroy

end
