class FlightsController < ApplicationController

  # skip the check for the authenticity token which is generated by the form_with
  # helper - we are submitting out form from our React frontend (eventually), so we won't have this token
  skip_before_action :verify_authenticity_token, raise: false

  def new
    @flight = Flight.new
  end #new

  def create
    @flight = Flight.create!(

      date: params[:flight][:date],
      flight: params[:flight][:flight],
      origin: params[:flight][:origin],
      destination: params[:flight][:destination],

    )
    redirect_to flights_path
  end #create

  def index
    render json: Flight.all
    # @flight = Flight.all

  end #index

  def show

    # @flight = Flight.where(["origin = ? and destination = ?", "SYD", "SUV"])
    flights = Flight.where(["origin = ? and destination = ?", params[:origin], params[:destination]])

    render json: flights
  end # show

  def select_seat
    booking = Flight.find(params[:id])

    render json: booking, include: [:airplane, :reservations]
  end # select_seat

  # def update

  # end #update

  def destroy
  end #destroy
end # class
