class UsersController < ApplicationController

  # skip the check for the authenticity token which is generated by the form_with 
    # helper - we are submitting out form from our React frontend (eventually), so we won't have this token
    skip_before_action :verify_authenticity_token, raise: false


  def new
  end # new

  def create
    user = User.create content: params[:content]

    if user.persisted?
        render json: user
    else
        render json: { error: 'Count not create user' }, status: 422
    end
  end # create

  def index
    
  end

  def show
    render json: User.all
  end # show

  def edit

  end # edit

  # def update
  # end

  def destroy

  end # destroy

end
